/**
 * Component (button + select menu) interaction handlers.
 *
 * Mirrors src/frontend/telegram/callbacks.ts. Settings panel callbacks update
 * the original message in place (Discord supports update() on the interaction).
 *
 * Custom-id namespace:
 *   settings:done
 *   settings:model      (select menu, value=modelId)
 *   settings:effort:<level>
 *   settings:proactive:on|off
 *   pulse:on | pulse:off
 *   effort:<level>
 *   model:select        (select menu, value=modelId)
 *
 * Other custom_ids fall through to the AI: pressing a button generated by
 * `send_message_with_buttons` translates to a "[Button pressed]" prompt for
 * the agent, just like Telegram callback_query messages.
 */

import {
  type ButtonInteraction,
  type StringSelectMenuInteraction,
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  StringSelectMenuBuilder,
  MessageFlags,
} from "discord.js";
import type { TalonConfig } from "../../util/config.js";
import type { Gateway } from "../../core/gateway.js";
import {
  getChatSettings,
  setChatModel,
  setChatEffort,
  resolveModelName,
  EFFORT_LEVELS,
  type EffortLevel,
} from "../../storage/chat-settings.js";
import {
  registerChat,
  disablePulse,
  enablePulse,
  isPulseEnabled,
} from "../../core/pulse.js";
import { isInteractionAllowed, registerDiscordChat } from "./handlers.js";
import { renderSettingsText } from "./helpers.js";
import { execute } from "../../core/dispatcher.js";
import { deriveNumericChatId } from "../../util/chat-id.js";
import { appendDailyLog } from "../../storage/daily-log.js";
import { logError } from "../../util/log.js";
import {
  suppressMentions,
  splitMessage,
  DISCORD_MAX_TEXT,
} from "./formatting.js";

type ComponentInteraction = ButtonInteraction | StringSelectMenuInteraction;

function chatIdFromInteraction(interaction: ComponentInteraction): {
  chatId: string;
  numericChatId: number;
} {
  const chatId = interaction.guildId
    ? `discord_guild_${interaction.guildId}_${interaction.channelId}`
    : `discord_dm_${interaction.user.id}`;
  return { chatId, numericChatId: deriveNumericChatId(chatId) };
}

export async function handleComponentInteraction(
  interaction: ComponentInteraction,
  config: TalonConfig,
  gateway: Gateway,
): Promise<void> {
  // Access control
  const access = isInteractionAllowed(
    interaction.inGuild(),
    interaction.user.id,
    interaction.guildId,
    interaction.channelId,
  );
  if (!access.ok) {
    await interaction.reply({
      content: `⚠️ ${access.reason}`,
      flags: MessageFlags.Ephemeral,
    });
    return;
  }

  const { chatId, numericChatId } = chatIdFromInteraction(interaction);
  registerDiscordChat({
    channelId: interaction.channelId!,
    guildId: interaction.guildId,
    userId: interaction.guildId ? null : interaction.user.id,
    numericChatId,
    chatId,
  });

  const customId = interaction.customId;

  // ── Settings panel callbacks ───────────────────────────────────────────────
  if (customId.startsWith("settings:")) {
    const parts = customId.split(":");
    const category = parts[1];

    if (category === "done") {
      try {
        await interaction.update({ components: [], content: "Done." });
      } catch {
        /* ignore */
      }
      return;
    }

    if (category === "model" && interaction.isStringSelectMenu()) {
      const value = interaction.values[0];
      if (value === "reset") {
        setChatModel(chatId, undefined);
      } else if (gateway?.backend?.resolveModel) {
        const resolution = await gateway.backend.resolveModel(value);
        if (resolution.kind !== "exact" || !resolution.model.selectable) {
          await interaction.reply({
            content: `Model unavailable.`,
            flags: MessageFlags.Ephemeral,
          });
          return;
        }
        setChatModel(chatId, resolution.storedValue);
      } else {
        setChatModel(chatId, resolveModelName(value));
      }
      await refreshSettingsPanel(interaction, config, gateway, chatId);
      return;
    }

    if (category === "effort") {
      const level = parts[2] ?? "";
      if (level === "adaptive") {
        setChatEffort(chatId, undefined);
      } else if (EFFORT_LEVELS.includes(level as EffortLevel)) {
        setChatEffort(chatId, level as EffortLevel);
      }
      await refreshSettingsPanel(interaction, config, gateway, chatId);
      return;
    }

    if (category === "proactive") {
      const value = parts[2] ?? "";
      if (value === "on") {
        enablePulse(chatId);
        registerChat(chatId);
      } else {
        disablePulse(chatId);
      }
      await refreshSettingsPanel(interaction, config, gateway, chatId);
      return;
    }
  }

  // ── Standalone /pulse buttons ─────────────────────────────────────────────
  if (customId.startsWith("pulse:")) {
    const val = customId.slice(6);
    if (val === "on") {
      enablePulse(chatId);
      registerChat(chatId);
    } else if (val === "off") {
      disablePulse(chatId);
    }
    const enabled = isPulseEnabled(chatId);
    const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId("pulse:on")
        .setLabel(enabled ? "✓ On" : "On")
        .setStyle(enabled ? ButtonStyle.Success : ButtonStyle.Secondary),
      new ButtonBuilder()
        .setCustomId("pulse:off")
        .setLabel(!enabled ? "✓ Off" : "Off")
        .setStyle(!enabled ? ButtonStyle.Danger : ButtonStyle.Secondary),
    );
    try {
      await (interaction as ButtonInteraction).update({
        content: [
          `**🔔 Pulse:** ${enabled ? "on" : "off"}`,
          "",
          "Reads along every few minutes and jumps in when there's something to add.",
        ].join("\n"),
        components: [row],
      });
    } catch {
      /* ignore */
    }
    return;
  }

  // ── Standalone /effort buttons ────────────────────────────────────────────
  if (customId.startsWith("effort:")) {
    const level = customId.slice(7);
    if (level === "adaptive") setChatEffort(chatId, undefined);
    else if (EFFORT_LEVELS.includes(level as EffortLevel))
      setChatEffort(chatId, level as EffortLevel);
    const current = getChatSettings(chatId).effort ?? "adaptive";
    const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
      ...(["off", "low", "medium", "high", "max", "adaptive"] as const).map(
        (v) =>
          new ButtonBuilder()
            .setCustomId(`effort:${v}`)
            .setLabel(current === v ? `✓ ${v}` : v)
            .setStyle(
              current === v ? ButtonStyle.Primary : ButtonStyle.Secondary,
            ),
      ),
    );
    try {
      await (interaction as ButtonInteraction).update({
        content: `**Effort:** ${current}`,
        components: [row],
      });
    } catch {
      /* ignore */
    }
    return;
  }

  // ── /model select-menu (separate from settings) ─────────────────────────
  if (customId === "model:select" && interaction.isStringSelectMenu()) {
    const value = interaction.values[0];
    if (value === "reset") {
      setChatModel(chatId, undefined);
    } else if (gateway?.backend?.resolveModel) {
      const resolution = await gateway.backend.resolveModel(value);
      if (resolution.kind === "exact" && resolution.model.selectable) {
        setChatModel(chatId, resolution.storedValue);
      } else {
        await interaction.reply({
          content: "Model unavailable.",
          flags: MessageFlags.Ephemeral,
        });
        return;
      }
    } else {
      setChatModel(chatId, resolveModelName(value));
    }

    const current = getChatSettings(chatId).model ?? config.model;
    const be = gateway?.backend;
    if (be?.getSettingsPresentation) {
      const pres = await be.getSettingsPresentation(current, "model:");
      const modelInfo = await be.getModelInfo?.(current);
      const displayName = modelInfo?.displayName ?? current;
      const menu = new StringSelectMenuBuilder()
        .setCustomId("model:select")
        .setPlaceholder("Pick a model")
        .addOptions(
          pres.modelButtons.slice(0, 25).map((b) => ({
            label: b.text.replace(/^✓ /, "").slice(0, 100),
            value: b.callback_data.replace(/^model:/, "").slice(0, 100),
            default: b.text.startsWith("✓"),
          })),
        );
      const row = new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(
        menu,
      );
      try {
        await interaction.update({
          content: [`**Model:** \`${displayName}\``, ...pres.modelDetails].join(
            "\n",
          ),
          components: [row],
        });
      } catch {
        /* ignore */
      }
    }
    return;
  }

  // ── Fallback: forward arbitrary button clicks to the AI ────────────────
  await forwardToAgent(interaction, gateway);
}

async function refreshSettingsPanel(
  interaction: ComponentInteraction,
  config: TalonConfig,
  gateway: Gateway,
  chatId: string,
): Promise<void> {
  const chatSets = getChatSettings(chatId);
  const activeModel = chatSets.model ?? config.model;
  const effortName = chatSets.effort ?? "adaptive";
  const pulseOn = isPulseEnabled(chatId);

  let modelDetails: Array<string> | undefined;
  let modelButtons: Array<{ text: string; callback_data: string }> | undefined;
  if (gateway?.backend?.getSettingsPresentation) {
    const pres = await gateway.backend.getSettingsPresentation(activeModel);
    modelDetails = pres.modelDetails;
    modelButtons = pres.modelButtons;
  }

  const components: ActionRowBuilder<
    StringSelectMenuBuilder | ButtonBuilder
  >[] = [];

  if (modelButtons?.length) {
    const menu = new StringSelectMenuBuilder()
      .setCustomId("settings:model")
      .setPlaceholder("Select a model")
      .addOptions(
        modelButtons.slice(0, 25).map((b) => ({
          label: b.text.replace(/^✓ /, "").slice(0, 100),
          value: b.callback_data.replace(/^settings:model:/, "").slice(0, 100),
          default: b.text.startsWith("✓"),
        })),
      );
    components.push(
      new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(menu),
    );
  }

  components.push(
    new ActionRowBuilder<ButtonBuilder>().addComponents(
      ...(["low", "medium", "high", "max", "adaptive"] as const).map((v) =>
        new ButtonBuilder()
          .setCustomId(`settings:effort:${v}`)
          .setLabel(effortName === v ? `✓ ${v}` : v)
          .setStyle(
            effortName === v ? ButtonStyle.Primary : ButtonStyle.Secondary,
          ),
      ),
    ),
  );

  components.push(
    new ActionRowBuilder<ButtonBuilder>().addComponents(
      new ButtonBuilder()
        .setCustomId(`settings:proactive:${pulseOn ? "off" : "on"}`)
        .setLabel(pulseOn ? "Pulse: ON" : "Pulse: OFF")
        .setStyle(pulseOn ? ButtonStyle.Success : ButtonStyle.Secondary),
      new ButtonBuilder()
        .setCustomId("settings:done")
        .setLabel("Done")
        .setStyle(ButtonStyle.Secondary),
    ),
  );

  try {
    await interaction.update({
      content: renderSettingsText(
        activeModel,
        effortName,
        pulseOn,
        chatSets.pulseIntervalMs,
        modelDetails,
      ),
      components,
    });
  } catch (err) {
    logError(
      "discord",
      `Failed to refresh settings panel: ${err instanceof Error ? err.message : err}`,
    );
  }
}

async function forwardToAgent(
  interaction: ComponentInteraction,
  _gateway: Gateway,
): Promise<void> {
  // Acknowledge so Discord doesn't show "interaction failed"
  try {
    await interaction.deferUpdate();
  } catch {
    /* might already be acked */
  }

  const { chatId, numericChatId } = chatIdFromInteraction(interaction);
  const sender =
    interaction.member?.user?.username ?? interaction.user.username ?? "User";
  const isGroup = interaction.guildId !== null;
  const customId = interaction.customId;
  const prompt = `[Button pressed] User clicked component with custom_id: "${customId}"`;
  const chatTitle = isGroup
    ? `${interaction.guild?.name ?? interaction.guildId} #${(interaction.channel as { name?: string } | null)?.name ?? interaction.channelId}`
    : undefined;

  appendDailyLog(sender, `Button: ${customId}`, { chatTitle });

  const onTextBlock = async (text: string) => {
    if (!text.trim()) return;
    if (!interaction.channel?.isSendable()) return;
    const chunks = splitMessage(suppressMentions(text), DISCORD_MAX_TEXT);
    for (const c of chunks) {
      try {
        await interaction.channel.send({
          content: c,
          allowedMentions: { parse: [] },
        });
      } catch (err) {
        logError(
          "discord",
          `forwardToAgent send failed: ${err instanceof Error ? err.message : err}`,
        );
      }
    }
  };

  try {
    await execute({
      chatId,
      numericChatId,
      prompt,
      senderName: sender,
      isGroup,
      source: "message",
      onTextBlock,
    });
  } catch (err) {
    logError(
      "discord",
      `Component → agent forward failed: ${err instanceof Error ? err.message : err}`,
    );
  }
}
